version: "3.8"

services:
  web:
    image: nginx:alpine
    container_name: web
    ports:
      - "8080:80"          # http://localhost:8080
    networks:
      - labnet

  client:
    image: alpine:3.20
    container_name: client
    # instala ferramentas e fica em espera para execuções via docker exec
    entrypoint: ["/bin/sh","-c","apk add --no-cache curl tcpdump iputils bind-tools && sleep infinity"]
    networks:
      - labnet
    volumes:
      - ./pcaps:/pcaps     # PCAPs salvos aqui no host

networks:
  labnet:
    driver: bridge
